login_project/login_app/urls.py
from django.urls import path
from login_app import views

app_name = 'login_app'

urlpatterns = [
    path('user_login/', views.user_login,name='user_login')
]

login_project/login_project/urls.py
from django.contrib import admin
from django.urls import path
from login_app import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name='home'),
    path('logout/', views.user_logout,name='logout'),
    path('',include('login_app.urls')),
]

login_project/login_app/models.py
from django.db import models

# Create your models here.

login_project/login_app/views.py
from django.shortcuts import render

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def home(request):
    return render(request,'login_app/home.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                context_dict ={'username':username}
                return render(request,'login_app/home.html',context_dict)
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed!")
            print("Username {} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request,'login_app/login.html',{})

login_project/templates/login_app/home.html
{% extends "login_app/navbar.html" %}
{% block body_block %}

<div class="container">
  {% if not user.is_authenticated %}
    <h5>You are not logged in. Please log in.</h5>
  {% else %}
    {% if username %}
      <h5>You're now logged in {{ username }}</h5>
    {% endif %}
  {% endif %}
  <h1>Welcome to my Website :)</h1>

</div>

{% endblock %}

login_project/templates/login_app/login.html
{% extends 'login_app/navbar.html' %}
{% block body_block %}

<div class="container">
  <h1>Please Login</h1>
  <form action="{% url 'login_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">
  </form>

</div>



{% endblock %}

login_project/templates/login_app/navbar.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  </head>
  <body>
    <nav>
      <div class="container">
        <ul class="nav">

          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>

          {% if user.is_authenticated %}
            <li>
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
          {% else %}
            <li>
              <a class="nav-link" href="{% url 'login_app:user_login' %}">Login</a>
            </li>
          {% endif %}

        </ul>
      </div>
    </nav>

    {% block body_block %}
    {% endblock %}

  </body>
</html>